# Generated by Django 6.0.4 on 2026-08-20 01:16

import markdownx.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0053_pubmedimportbatch_last_pubmed_fetched_at_and_more'),
        ('submissions', '0056_backfill_review_publish_date_from_first_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('speaker', models.CharField(blank=True, max_length=255)),
                ('chair', models.CharField(blank=True, max_length=255)),
                ('description', markdownx.models.MarkdownxField(blank=True)),
                ('pre_reading_note', models.CharField(blank=True, help_text="Short line shown above the pre-reading list, e.g. 'Pre-reading is not essential.'", max_length=255)),
                ('event_url', models.URLField(blank=True, help_text='Link to the SPANZA event page for registration and details.', max_length=500)),
                ('extra_reading', markdownx.models.MarkdownxField(blank=True, help_text='Additional reading not held in the article database (markdown).')),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, help_text='Papers offered as pre-reading that have no Journal Watch review.', related_name='live_sessions', to='backend.pubmedarticle')),
                ('reviews', models.ManyToManyField(blank=True, help_text='Journal Watch reviews offered as pre-reading.', related_name='live_sessions', to='submissions.review')),
            ],
            options={
                'ordering': ('display_order', 'start_datetime'),
            },
        ),
    ]
