# Generated by Django 6.0.4 on 2026-08-20 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_pubmedimportbatch_last_pubmed_fetched_at_and_more'),
        ('events', '0001_initial'),
        ('submissions', '0056_backfill_review_publish_date_from_first_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livesession',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='extra_reading',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='reviews',
        ),
        migrations.CreateModel(
            name='LiveSessionReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('topic', models.CharField(blank=True, help_text='Short discussion-topic label shown above the paper.', max_length=120)),
                ('prompt', models.TextField(blank=True, help_text='Discussion questions posed to readers ahead of the session.')),
                ('title', models.CharField(blank=True, help_text='Paper title, for papers not linked above.', max_length=500)),
                ('source', models.CharField(blank=True, help_text='Journal and year, for papers not linked above.', max_length=255)),
                ('url', models.URLField(blank=True, help_text='Full-text link, for papers not linked above.', max_length=500)),
                ('pubmed_url', models.URLField(blank=True, help_text='PubMed link, for papers not linked above.', max_length=500)),
                ('review_url', models.URLField(blank=True, help_text='Link to a Journal Watch review, if not linked above.', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('article', models.ForeignKey(blank=True, help_text='Paper in the article database, if it has no review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_readings', to='backend.pubmedarticle')),
                ('review', models.ForeignKey(blank=True, help_text='Journal Watch review of the paper, if one exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_readings', to='submissions.review')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='events.livesession')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
