# Generated by Django 6.0.4 on 2026-08-20 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_livesession_articles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='registration_note',
            field=models.TextField(blank=True, help_text='Short registration summary shown with the register button, e.g. fees and inclusions.'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='registration_url',
            field=models.URLField(blank=True, help_text='Link to the online registration form.', max_length=500),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='event_url',
            field=models.URLField(blank=True, help_text='Link to the SPANZA event page with full event information.', max_length=500),
        ),
    ]
