version: '3'

volumes:
  spanza_journal_watch_local_postgres_data: {}
  spanza_journal_watch_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: spanza_journal_watch_local_django
    container_name: spanza_journal_watch_local_django
    depends_on:
      - postgres
      - redis
      - mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spanza_journal_watch_production_postgres
    container_name: spanza_journal_watch_local_postgres
    volumes:
      - spanza_journal_watch_local_postgres_data:/var/lib/postgresql/data
      - spanza_journal_watch_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: spanza_journal_watch_local_docs
    container_name: spanza_journal_watch_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./spanza_journal_watch:/app/spanza_journal_watch:z
    ports:
      - '9000:9000'
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: spanza_journal_watch_local_mailhog
    ports:
      - '8025:8025'

  redis:
    image: redis:6
    container_name: spanza_journal_watch_local_redis

  celeryworker:
    <<: *django
    image: spanza_journal_watch_local_celeryworker
    container_name: spanza_journal_watch_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: spanza_journal_watch_local_celerybeat
    container_name: spanza_journal_watch_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: spanza_journal_watch_local_flower
    container_name: spanza_journal_watch_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: spanza_journal_watch_local_node
    container_name: spanza_journal_watch_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
