version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  access_logs: {} # Add a new volume definition for the logs

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: spanza_journal_watch_production_django
    depends_on:
      - postgres
      - redis
      - mjml
    volumes:
      - access_logs:/app/access_logs # Map the logs directory on the host to /app/logs inside the container
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - internal_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: spanza_journal_watch_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - internal_network

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: spanza_journal_watch_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
      - '0.0.0.0:5555:5555'

  redis:
    image: redis:6

  celeryworker:
    <<: *django
    image: spanza_journal_watch_production_celeryworker
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: spanza_journal_watch_production_celerybeat
    command: /start-celerybeat

  flower:
    <<: *django
    image: spanza_journal_watch_production_flower
    command: /start-flower

  awscli:
    build:
      context: .
      dockerfile: ./compose/production/aws/Dockerfile
    env_file:
      - ./.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

  mjml:
    build:
      context: .
      dockerfile: ./compose/production/mjml-tcp/Dockerfile
    image: spanza_journal_watch_production_mjml
    container_name: spanza_journal_watch_production_mjml
    restart: always
    ports:
      - '28101:28101'
    networks:
      - internal_network
    command: ['--mjml.minify=true', '--mjml.validationLevel=strict']

networks:
  internal_network:
