# Generated by Django 4.1.9 on 2023-06-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="anonymous_author",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="health_services",
            field=models.ManyToManyField(related_name="health_services", to="users.healthservice"),
        ),
    ]
