# Generated by Django 4.1.9 on 2023-07-14 00:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_healthservice_user_anonymous_author_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="anonymous_author",
        ),
        migrations.RemoveField(
            model_name="user",
            name="health_services",
        ),
        migrations.DeleteModel(
            name="HealthService",
        ),
    ]
