# Generated by Django 6.0.3 on 2026-03-30 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0032_backendpreference_frontend_banner_enabled_and_more"),
        ("users", "0003_remove_user_anonymous_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="watched_journals",
            field=models.ManyToManyField(
                blank=True, related_name="watching_users", to="backend.watchedjournal"
            ),
        ),
    ]
