# Generated by Django 6.0.3 on 2026-04-01 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_add_read_at_to_pubmedarticleuserstate'),
        ('users', '0004_user_watched_journals'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_viewed_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backend.watchedjournal'),
        ),
    ]
