# Generated by Django 6.0.3 on 2026-04-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_last_viewed_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cpd_tracking_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_spanza_member',
            field=models.BooleanField(default=False),
        ),
    ]
