# Generated by Django 4.1.9 on 2023-06-07 12:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0003_alter_homepage_card_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="created",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="homepage",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
