# Generated by Django 4.1.9 on 2023-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0005_remove_homepage_card_features_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="featurearticle",
            name="image",
            field=models.ImageField(
                blank=True,
                height_field="image_height",
                null=True,
                upload_to="uploads/featurearticle/",
                width_field="image_width",
            ),
        ),
    ]
