# Generated by Django 4.1.9 on 2023-07-04 02:43

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0007_featurearticle_image_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="featurearticle",
            name="image_height",
        ),
        migrations.RemoveField(
            model_name="featurearticle",
            name="image_width",
        ),
        migrations.AlterField(
            model_name="featurearticle",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
            ),
        ),
    ]
