# Generated by Django 4.1.9 on 2023-07-04 16:22

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0008_remove_featurearticle_image_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
                    ),
                ),
                ("url_stem", models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
