# Generated by Django 4.1.9 on 2023-07-05 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0009_pageheader"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssuePage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay_light", models.TextField()),
                ("overlay_dark", models.TextField()),
                ("additional_css", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReviewPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay_light", models.TextField()),
                ("overlay_dark", models.TextField()),
                ("additional_css", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SearchPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay_light", models.TextField()),
                ("overlay_dark", models.TextField()),
                ("additional_css", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TagPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay_light", models.TextField()),
                ("overlay_dark", models.TextField()),
                ("additional_css", models.TextField()),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="PageHeader",
        ),
    ]
