# Generated by Django 4.1.9 on 2023-07-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0010_issuepage_reviewpage_searchpage_tagpage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuepage",
            name="additional_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issuepage",
            name="overlay_dark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issuepage",
            name="overlay_light",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewpage",
            name="additional_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewpage",
            name="overlay_dark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewpage",
            name="overlay_light",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="additional_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="overlay_dark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="searchpage",
            name="overlay_light",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tagpage",
            name="additional_css",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tagpage",
            name="overlay_dark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tagpage",
            name="overlay_light",
            field=models.TextField(blank=True, null=True),
        ),
    ]
