# Generated by Django 4.1.9 on 2023-07-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0011_alter_issuepage_additional_css_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueDetailPage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("overlay_light", models.TextField(blank=True, null=True)),
                ("overlay_dark", models.TextField(blank=True, null=True)),
                ("additional_css", models.TextField(blank=True, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
