# Generated by Django 4.1.9 on 2023-07-08 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0013_homepagepage_homepage_homepage_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="main_feature",
        ),
    ]
