# Generated by Django 4.1.9 on 2023-07-09 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0014_remove_homepage_main_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gradient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("gradient_name", models.CharField(max_length=255)),
                ("background_css", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="homepagepage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="homepagepage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="issuedetailpage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="issuedetailpage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="issuepage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="issuepage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="reviewpage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="reviewpage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="searchpage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="searchpage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="tagpage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
        migrations.AddField(
            model_name="tagpage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.gradient"
            ),
        ),
    ]
