# Generated by Django 4.1.9 on 2023-07-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0016_remove_homepagepage_dark_gradient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagepage",
            name="dark_gradient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_page_dark",
                to="layout.gradient",
            ),
        ),
        migrations.AddField(
            model_name="homepagepage",
            name="light_gradient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homepage_page_light",
                to="layout.gradient",
            ),
        ),
    ]
