# Generated by Django 4.1.9 on 2023-07-09 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0017_homepagepage_dark_gradient_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gradient",
            old_name="gradient_name",
            new_name="name",
        ),
    ]
