# Generated by Django 4.1.9 on 2023-07-12 03:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0019_rename_background_css_gradient_css"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepagepage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="homepagepage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="homepagepage",
            name="overlay_light",
        ),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="overlay_light",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="overlay_light",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="overlay_light",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="overlay_light",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="additional_css",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="overlay_dark",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="overlay_light",
        ),
    ]
