# Generated by Django 4.2.5 on 2026-03-15 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0020_remove_homepagepage_additional_css_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="homepage_page",
        ),
        migrations.RemoveField(
            model_name="homepagepage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="homepagepage",
            name="light_gradient",
        ),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="light_gradient",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="light_gradient",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="light_gradient",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="light_gradient",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="dark_gradient",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="light_gradient",
        ),
        migrations.DeleteModel(
            name="Gradient",
        ),
    ]
