# Generated by Django 4.2.5 on 2026-03-15 08:19

from django.db import migrations, models
import django.db.models.deletion


def copy_page_headers(apps, schema_editor):
    PageHeader = apps.get_model("layout", "PageHeader")
    model_map = {
        "HomepagePage": "home",
        "SearchPage": "search",
        "IssuePage": "issue_list",
        "IssueDetailPage": "issue_detail",
        "ReviewPage": "review_detail",
        "TagPage": "tag",
    }

    for model_name, page_type in model_map.items():
        Model = apps.get_model("layout", model_name)
        rows = Model.objects.all().values("feature_article_id", "active", "created", "modified")
        PageHeader.objects.bulk_create(
            [
                PageHeader(
                    page_type=page_type,
                    feature_article_id=row["feature_article_id"],
                    active=row["active"],
                    created=row["created"],
                    modified=row["modified"],
                )
                for row in rows
            ]
        )


def noop_reverse(apps, schema_editor):
    # Legacy page models are removed in this migration; reverse data copy is intentionally unsupported.
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0021_remove_homepage_homepage_page_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageHeader",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("active", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("search", "Search"),
                            ("issue_list", "Issue list"),
                            ("issue_detail", "Issue detail"),
                            ("review_detail", "Review detail"),
                            ("tag", "Tag pages"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "feature_article",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(copy_page_headers, noop_reverse),
        migrations.RemoveField(
            model_name="issuedetailpage",
            name="feature_article",
        ),
        migrations.RemoveField(
            model_name="issuepage",
            name="feature_article",
        ),
        migrations.RemoveField(
            model_name="reviewpage",
            name="feature_article",
        ),
        migrations.RemoveField(
            model_name="searchpage",
            name="feature_article",
        ),
        migrations.RemoveField(
            model_name="tagpage",
            name="feature_article",
        ),
        migrations.DeleteModel(
            name="HomepagePage",
        ),
        migrations.DeleteModel(
            name="IssueDetailPage",
        ),
        migrations.DeleteModel(
            name="IssuePage",
        ),
        migrations.DeleteModel(
            name="ReviewPage",
        ),
        migrations.DeleteModel(
            name="SearchPage",
        ),
        migrations.DeleteModel(
            name="TagPage",
        ),
    ]
