# Generated by Django 6.0.3 on 2026-03-25 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("layout", "0022_pageheader_remove_issuedetailpage_feature_article_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="override_main",
        ),
    ]
