# Generated by Django 4.1.9 on 2023-08-08 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0031_alter_hit_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=255)),
                ("subscribed", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("unsubscribe_token", models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("send_date", models.DateTimeField()),
                ("ready_to_send", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("is_test_sent", models.BooleanField(default=False)),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submissions.issue")),
            ],
        ),
    ]
