# Generated by Django 4.1.9 on 2023-08-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="send_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
