# Generated by Django 4.1.9 on 2023-08-25 15:08

from django.db import migrations, models
import django.db.models.deletion
import spanza_journal_watch.newsletter.models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0002_alter_newsletter_send_date"),
    ]

    operations = [ 
        migrations.AddField(
            model_name="subscriber",
            name="bounced",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="complained",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriber",
            name="tester",
            field=models.BooleanField(default=False),
        ),
    ]
