# Generated by Django 4.1.9 on 2023-08-28 13:22

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_emailfont_emailimage_subscriber_bounced_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="newsletter",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="header_image_processed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
