# Generated by Django 4.1.9 on 2023-08-28 13:22

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0003_emailfont_emailimage_subscriber_bounced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="header_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="header_image_processed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
