# Generated by Django 4.1.9 on 2023-08-28 16:15

from django.db import migrations, models
import django.db.models.deletion
import spanza_journal_watch.newsletter.models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0031_alter_hit_options"),
        ("newsletter", "0004_logo_newsletter_header_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="content_heading",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Heading for the introductory content"
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                default=spanza_journal_watch.newsletter.models.Logo.get_latest_logo,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="newsletter.logo",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="non_featured_review_count",
            field=models.PositiveIntegerField(blank=True, default=5, null=True),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="content",
            field=models.TextField(verbose_name="Introductory content paragraph"),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="issue",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="submissions.issue"),
        ),
    ]
