# Generated by Django 4.1.9 on 2023-08-29 05:46

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0005_newsletter_content_heading_newsletter_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElementImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("UP", "Up chevron"), ("DN", "Down chevron"), ("LO", "Logo"), ("OT", "Other")],
                        default="OT",
                        max_length=2,
                        unique=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
                    ),
                ),
            ],
        ),
    ]
