# Generated by Django 4.1.9 on 2023-08-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0007_alter_newsletter_header_image_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="elementimage",
            name="type",
            field=models.CharField(
                choices=[
                    ("UP", "Up chevron"),
                    ("DN", "Down chevron"),
                    ("LO", "Logo"),
                    ("HE", "Heading"),
                    ("OT", "Other"),
                ],
                default="OT",
                max_length=2,
                unique=True,
            ),
        ),
    ]
