# Generated by Django 4.1.9 on 2023-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0010_subscriber_from_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="send_token",
            field=models.CharField(default="", editable=False, max_length=64, unique=True),
        ),
    ]
