# Generated by Django 4.1.9 on 2023-09-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0011_newsletter_send_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="emails_sent",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
