# Generated by Django 4.2.5 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0012_newsletter_emails_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="resend_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
