# Generated by Django 5.2 on 2026-03-16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0013_newsletter_resend_enabled"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ElementImage",
        ),
    ]
