# Generated by Django 6.0.3 on 2026-04-18 12:00

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0015_add_subscriber_user_fk"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                django.db.models.functions.text.Upper("email"),
                name="newsletter_sub_email_upper_idx",
            ),
        ),
    ]
