# Generated by Django 6.0.4 on 2026-04-23 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0017_remove_newsletter_send_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='source',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('drawer', 'Drawer'), ('subscribe_form', 'Subscribe form'), ('csv_import', 'CSV import'), ('user_signup', 'User signup')], db_index=True, default='unknown', max_length=32),
        ),
    ]
