# Generated by Django 6.0.4 on 2026-04-23 23:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_subscribercsv_task_state'),
        ('newsletter', '0019_backfill_subscriber_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['created'], name='newsletter_sub_created_idx'),
        ),
    ]
