# Generated by Django 6.0.4 on 2026-09-15 06:49

import django.db.models.deletion
import base64
import uuid

from django.db import migrations, models


def backfill_tracking_tokens(apps, schema_editor):
    Subscriber = apps.get_model("newsletter", "Subscriber")
    batch = []
    for subscriber in Subscriber.objects.filter(tracking_token__isnull=True).only("pk").iterator():
        subscriber.tracking_token = base64.urlsafe_b64encode(uuid.uuid4().bytes).decode("utf-8").replace("=", "")
        batch.append(subscriber)
        if len(batch) >= 500:
            Subscriber.objects.bulk_update(batch, ["tracking_token"])
            batch = []
    if batch:
        Subscriber.objects.bulk_update(batch, ["tracking_token"])


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0020_subscriber_newsletter_sub_created_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriber",
            name="tracking_token",
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="NewsletterDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="newsletter.newsletter",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletter_deliveries",
                        to="newsletter.subscriber",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("newsletter", "subscriber"), name="newsletter_delivery_unique")
                ],
            },
        ),
        migrations.RunPython(backfill_tracking_tokens, migrations.RunPython.noop),
    ]
