from django.urls import path

from spanza_journal_watch.backend import analytics_views

from . import views

app_name = "backend"
urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("go/", views.backend_go, name="backend_go"),
    path("articles/watched-journals", views.watched_journals, name="watched_journals"),
    path("articles/watched-journals/search", views.watched_journal_search, name="watched_journal_search"),
    path(
        "articles/watched-journals/<int:watched_journal_id>/toggle-active",
        views.watched_journal_toggle_active,
        name="watched_journal_toggle_active",
    ),
    path("articles/intake", views.article_intake, name="article_intake"),
    path("articles/intake/pubmed-api-key", views.pubmed_save_api_key, name="pubmed_save_api_key"),
    path("articles/intake/<int:batch_id>/results", views.article_intake_results, name="article_intake_results"),
    path("articles/intake/<int:batch_id>/find", views.article_intake_find_article, name="article_intake_find_article"),
    path(
        "articles/intake/<int:batch_id>/add-article",
        views.article_intake_add_article,
        name="article_intake_add_article",
    ),
    path(
        "articles/intake/<int:batch_id>/select/<int:item_id>",
        views.article_intake_toggle_selection,
        name="article_intake_toggle_selection",
    ),
    path(
        "articles/intake/<int:batch_id>/bulk-select",
        views.article_intake_bulk_selection,
        name="article_intake_bulk_selection",
    ),
    path(
        "articles/intake/<int:batch_id>/assign-issue",
        views.article_intake_assign_issue,
        name="article_intake_assign_issue",
    ),
    path(
        "articles/intake/<int:batch_id>/refresh",
        views.article_intake_refresh_batch,
        name="article_intake_refresh_batch",
    ),
    path(
        "articles/intake/<int:batch_id>/push-to-planka",
        views.article_intake_push_to_planka,
        name="article_intake_push_to_planka",
    ),
    path(
        "articles/intake/<int:batch_id>/reconcile-planka-status",
        views.article_intake_reconcile_planka_status,
        name="article_intake_reconcile_planka_status",
    ),
    path(
        "articles/intake/<int:batch_id>/task-status",
        views.article_intake_task_status,
        name="article_intake_task_status",
    ),
    path("settings", views.backend_settings, name="backend_settings"),
    path("settings/inbox-sender", views.save_inbox_sender_settings, name="save_inbox_sender_settings"),
    path("issues/builder", views.issue_builder, name="issue_builder"),
    path("issues/reviewers", views.issue_reviewers, name="issue_reviewers"),
    path("issues/reviews", views.issue_reviews_edit, name="issue_reviews_edit"),
    path("issues/publish", views.issue_publish, name="issue_publish"),
    path("issues/set-homepage", views.issue_set_homepage, name="issue_set_homepage"),
    path("issues/reviews/<int:review_id>/toggle", views.toggle_review_active, name="toggle_review_active"),
    path("issues/planka", views.issue_planka_import, name="issue_planka_import"),
    path("issues/builder/save", views.save_issue_draft, name="save_issue_draft"),
    path("issues/builder/<int:issue_id>/save", views.save_issue_draft, name="update_issue_draft"),
    path("issues/builder/<int:issue_id>/reviews/new", views.new_review_form, name="new_issue_review_form"),
    path("issues/builder/<int:issue_id>/reviews/add", views.add_issue_review, name="add_issue_review"),
    path(
        "issues/builder/<int:issue_id>/reviews/<int:review_id>/edit",
        views.edit_issue_review_form,
        name="edit_issue_review_form",
    ),
    path(
        "issues/builder/<int:issue_id>/reviews/<int:review_id>/update",
        views.update_issue_review,
        name="update_issue_review",
    ),
    path(
        "issues/builder/<int:issue_id>/reviews/<int:review_id>/remove",
        views.remove_issue_review,
        name="remove_issue_review",
    ),
    path(
        "issues/builder/<int:issue_id>/contributors/add",
        views.issue_add_contributor,
        name="issue_add_contributor",
    ),
    path(
        "issues/builder/<int:issue_id>/contributors/send-invites",
        views.issue_send_contributor_invites,
        name="issue_send_contributor_invites",
    ),
    path(
        "issues/builder/<int:issue_id>/contributors/<int:contributor_id>/resend",
        views.issue_resend_contributor_invite,
        name="issue_resend_contributor_invite",
    ),
    path(
        "issues/builder/<int:issue_id>/contributors/<int:contributor_id>/revoke",
        views.issue_revoke_contributor,
        name="issue_revoke_contributor",
    ),
    path(
        "issues/builder/<int:issue_id>/contributors/<int:contributor_id>/sync-planka",
        views.issue_sync_contributor_planka,
        name="issue_sync_contributor_planka",
    ),
    path("issues/builder/<int:issue_id>/publish", views.publish_issue_bundle, name="publish_issue_bundle"),
    path(
        "issues/builder/<int:issue_id>/planka/setup",
        views.planka_setup_issue_project,
        name="planka_setup_issue_project",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/recreate-board",
        views.planka_recreate_issue_board,
        name="planka_recreate_issue_board",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/publish-cards",
        views.planka_refresh_publish_cards,
        name="planka_refresh_publish_cards",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/background",
        views.planka_update_project_background,
        name="planka_update_project_background",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/project-name",
        views.planka_update_project_name,
        name="planka_update_project_name",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/import-card",
        views.planka_import_publish_card,
        name="planka_import_publish_card",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/import-cards",
        views.planka_import_publish_cards_bulk,
        name="planka_import_publish_cards_bulk",
    ),
    path("subscribers/upload", views.upload_subscriber_csv, name="upload_subscribers"),
    path("subscribers/list", views.subscriber_list, name="subscriber_list"),
    path("subscribers/upload/change-header/<str:save_token>", views.edit_csv_header, name="edit_csv_header"),
    path("subscribers/upload/process-csv/<str:save_token>", views.process_csv, name="process_csv"),
    path("newsletter/release", views.newsletter_release_list, name="newsletter_release_list"),
    path("newsletter/release/create", views.create_newsletter, name="create_newsletter"),
    path("newsletter/send/<str:send_token>", views.final_newsletter, name="final_newsletter"),
    path("newsletter/send/test/<str:send_token>", views.send_test_newsletter, name="send_test_newsletter"),
    path(
        "newsletter/send/enable-resend/<str:send_token>",
        views.enable_newsletter_resend,
        name="enable_newsletter_resend",
    ),
    path("newsletter/send/confirm/<str:send_token>", views.send_final_newsletter, name="send_final_newsletter"),
    path("newsletter/stats", views.newsletter_stats_list_redirect, name="newsletter_stats_list"),
    path("newsletter/stats/<int:pk>", views.newsletter_stats_detail, name="newsletter_stats_detail"),
    path("analytics", views.analytics_redirect, name="site_analytics"),
    path("analytics/overview/", analytics_views.analytics_overview, name="analytics_overview"),
    path("analytics/content/", analytics_views.analytics_content, name="analytics_content"),
    path("analytics/traffic/", analytics_views.analytics_traffic, name="analytics_traffic"),
    path("analytics/email/", analytics_views.analytics_email, name="analytics_email"),
    path("analytics/search/", analytics_views.analytics_search, name="analytics_search"),
    path("analytics/journals/", analytics_views.analytics_journals, name="analytics_journals"),
    path("settings/run/planka-oidc", views.planka_run_setup_oidc, name="planka_run_setup_oidc"),
    path("settings/run/planka-api-key", views.planka_run_setup_api_key, name="planka_run_setup_api_key"),
    path(
        "settings/run/planka-promote-chief-editor",
        views.planka_promote_chief_editor,
        name="planka_promote_chief_editor",
    ),
    path("contributors/author-lookup", views.contributor_author_lookup, name="contributor_author_lookup"),
    path("affiliations", views.affiliations_list, name="affiliations_list"),
    path("affiliations/<int:affiliation_id>/edit", views.affiliation_edit, name="affiliation_edit"),
    path("authors", views.authors_list, name="authors_list"),
    path("authors/<int:author_id>/edit", views.author_edit, name="author_edit"),
    path(
        "webhooks/planka/card-update",
        views.planka_card_update_webhook,
        name="planka_card_update_webhook",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/cards/<str:card_id>/revisions",
        views.planka_card_revisions,
        name="planka_card_revisions",
    ),
    path(
        "issues/builder/<int:issue_id>/planka/revisions/<int:revision_id>/restore",
        views.planka_card_revision_restore,
        name="planka_card_revision_restore",
    ),
    path("inbox/", views.inbox, name="inbox"),
    path("inbox/mark-all-read", views.inbox_mark_all_read, name="inbox_mark_all_read"),
    path("inbox/<int:thread_id>/", views.inbox_thread, name="inbox_thread"),
    path("inbox/<int:thread_id>/reply", views.inbox_reply, name="inbox_reply"),
    path("docs/", views.serve_docs, name="docs"),
    path("docs/<path:path>", views.serve_docs, name="docs_file"),
]
