# Generated by Django 4.1.9 on 2023-06-10 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0005_remove_homepage_card_features_and_more"),
        ("submissions", "0002_issue_main_feature_review_is_featured"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="main_feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_features",
                related_query_name="main_feature",
                to="layout.featurearticle",
            ),
        ),
    ]
