# Generated by Django 4.1.9 on 2023-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0004_alter_article_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
