# Generated by Django 4.1.9 on 2023-09-12 23:57

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriberCSV",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=spanza_journal_watch.utils.modelmethods.name_csv)),
                ("confirmed", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("email_count", models.PositiveIntegerField()),
                ("email_added_count", models.PositiveIntegerField()),
            ],
            options={
                "permissions": [("manage_subscriber_csv", "Can create and edit CSV subscriber lists")],
            },
        ),
    ]
