# Generated by Django 4.1.9 on 2023-09-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribercsv",
            name="save_token",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
