# Generated by Django 4.1.9 on 2023-09-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_subscribercsv_save_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribercsv",
            name="email_added_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscribercsv",
            name="email_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
