# Generated by Django 4.1.9 on 2023-09-14 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_rename_email_count_subscribercsv_row_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribercsv",
            options={
                "permissions": [
                    ("manage_subscriber_csv", "Can create and edit CSV subscriber lists"),
                    ("send_newsletters", "Can send out newsletters to all subscribers"),
                ]
            },
        ),
    ]
