# Generated by Django 4.2.5 on 2023-09-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_alter_subscribercsv_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender", models.EmailField(blank=True, max_length=254, null=True)),
                ("recipient", models.EmailField(blank=True, max_length=254, null=True)),
                ("header_sender", models.CharField(blank=True, max_length=255, null=True)),
                ("header_recipients", models.TextField(blank=True, null=True)),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField(blank=True, null=True)),
                ("body_html", models.TextField(blank=True, null=True)),
                ("sent_timestamp", models.DateTimeField(blank=True, null=True)),
                ("attachments", models.BooleanField(default=False)),
                ("email_file", models.CharField(blank=True, max_length=255, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
