# Generated by Django 6.0.3 on 2026-03-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_alter_subscribercsv_options"),
        ("submissions", "0037_alter_issue_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlankaIssueBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("project_id", models.CharField(max_length=64, unique=True)),
                ("project_name", models.CharField(max_length=255)),
                ("board_id", models.CharField(max_length=64, unique=True)),
                ("board_name", models.CharField(default="Reviews", max_length=128)),
                ("lists", models.JSONField(blank=True, default=dict)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("custom_field_group_id", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "issue",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planka_binding",
                        to="submissions.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planka Issue Binding",
                "verbose_name_plural": "Planka Issue Bindings",
            },
        ),
        migrations.CreateModel(
            name="PlankaCardImport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("card_id", models.CharField(max_length=64, unique=True)),
                ("card_name", models.CharField(max_length=1024)),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planka_imports",
                        to="submissions.issue",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planka_imports",
                        to="submissions.review",
                    ),
                ),
                (
                    "binding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imports",
                        to="backend.plankaissuebinding",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planka Card Import",
                "verbose_name_plural": "Planka Card Imports",
                "ordering": ("-created",),
            },
        ),
    ]
