# Generated by Django 6.0.3 on 2026-03-16 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_plankaissuebinding_plankacardimport"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlankaIntegrationCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("singleton", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                (
                    "auth_mode",
                    models.CharField(
                        choices=[("password", "Username/password"), ("oidc", "OIDC code exchange")], max_length=24
                    ),
                ),
                ("api_key", models.TextField()),
                ("api_key_prefix", models.CharField(blank=True, max_length=32)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_planka_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planka Integration Credential",
                "verbose_name_plural": "Planka Integration Credentials",
            },
        ),
    ]
