# Generated by Django 6.0.3 on 2026-03-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_plankaintegrationcredential"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plankaissuebinding",
            name="instructions_board_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="plankaissuebinding",
            name="instructions_board_name",
            field=models.CharField(default="Instructions", max_length=128),
        ),
        migrations.AddField(
            model_name="plankaissuebinding",
            name="instructions_lists",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="PlankaBoardBackgroundAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="backend/planka/backgrounds")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_planka_background_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Planka Board Background Asset",
                "verbose_name_plural": "Planka Board Background Assets",
                "ordering": ("name", "-created"),
            },
        ),
    ]
