# Generated by Django 6.0.3 on 2026-03-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_plankaboardbackgroundasset_and_binding_extensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="plankaissuebinding",
            name="background_asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_bindings",
                to="backend.plankaboardbackgroundasset",
            ),
        ),
    ]
