# Generated by Django 6.0.3 on 2026-03-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_plankaissuebinding_background_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="plankacardimport",
            name="last_card_payload_hash",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="plankacardimport",
            name="last_review_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
