# Generated by Django 6.0.3 on 2026-03-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_plankacardimport_sync_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plankaintegrationcredential",
            name="auth_mode",
            field=models.CharField(
                choices=[
                    ("api_key", "Manual API key"),
                    ("password", "Username/password"),
                    ("oidc", "OIDC code exchange"),
                ],
                max_length=24,
            ),
        ),
    ]
