# Generated by Django 5.2.6 on 2026-03-17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0037_alter_issue_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("backend", "0015_alter_plankaintegrationcredential_auth_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="PubmedArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("pmid", models.CharField(max_length=32, unique=True)),
                ("doi", models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ("title", models.TextField(blank=True)),
                ("abstract", models.TextField(blank=True)),
                ("source_journal_name", models.CharField(blank=True, max_length=255)),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("publication_month", models.DateField(blank=True, null=True)),
                ("article_url", models.URLField(blank=True, max_length=500)),
                ("pubmed_url", models.URLField(blank=True, max_length=500)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ("-publication_date", "-created"),
            },
        ),
        migrations.CreateModel(
            name="PubmedImportBatch",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("from_month", models.DateField()),
                ("to_month", models.DateField()),
                ("keyword_query", models.CharField(blank=True, max_length=255)),
                ("result_count", models.PositiveIntegerField(default=0)),
                ("selected_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pubmed_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pubmed_import_batches",
                        to="submissions.issue",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
            },
        ),
        migrations.CreateModel(
            name="PubmedIntegrationCredential",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("singleton", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("api_key", models.TextField(blank=True)),
                ("last_validated_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "configured_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="configured_pubmed_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PubMed Integration Credential",
                "verbose_name_plural": "PubMed Integration Credentials",
            },
        ),
        migrations.CreateModel(
            name="WatchedJournal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("issn_print", models.CharField(blank=True, max_length=32)),
                ("issn_electronic", models.CharField(blank=True, max_length=32)),
                ("pubmed_query_override", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                (
                    "journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="watched_sources",
                        to="submissions.journal",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PubmedBatchArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_links",
                        to="backend.pubmedarticle",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_articles",
                        to="backend.pubmedimportbatch",
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pubmed_batch_articles",
                        to="submissions.issue",
                    ),
                ),
                (
                    "watched_journal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batch_articles",
                        to="backend.watchedjournal",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "constraints": [
                    models.UniqueConstraint(fields=("batch", "article"), name="uniq_pubmed_batch_article")
                ],
            },
        ),
        migrations.AddField(
            model_name="pubmedimportbatch",
            name="watched_journals",
            field=models.ManyToManyField(blank=True, related_name="import_batches", to="backend.watchedjournal"),
        ),
    ]
