# Generated by Django 6.0.3 on 2026-03-20 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0022_issuecontributor_issuecontributorinvite_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecontributor",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="issuecontributor",
            name="planka_membership_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
