# Generated by Django 6.0.3 on 2026-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0023_issuecontributor_name_planka_membership"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecontributor",
            name="planka_instructions_membership_id",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
