# Generated by Django 6.0.3 on 2026-03-21 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0026_fix_newsletter_stats_permission_typo"),
        ("submissions", "0041_author_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuecontributor",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked Author profile (auto-matched by email on invite acceptance)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contributor_memberships",
                to="submissions.author",
            ),
        ),
        migrations.AlterField(
            model_name="issuecontributor",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("invited", "Invited"),
                    ("active", "Active"),
                    ("revoked", "Revoked"),
                    ("expired", "Expired"),
                ],
                default="invited",
                max_length=24,
            ),
        ),
    ]
