# Generated by Django 4.2.5 on 2026-03-29 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0029_emailthread_sentemail_inboundemail_inbox_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="backendpreference",
            name="inbox_from_address",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="inbox_from_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
