# Generated by Django 6.0.3 on 2026-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_backendpreference_inbox_from_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='plankacardrevision',
            new_name='backend_pla_card_id_7e39ed_idx',
            old_name='backend_pla_card_id_idx',
        ),
    ]
