# Generated by Django 6.0.3 on 2026-03-30 02:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0031_rename_backend_pla_card_id_idx_backend_pla_card_id_7e39ed_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_link_text",
            field=models.CharField(blank=True, default="", max_length=80),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_link_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_title",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="backendpreference",
            name="frontend_banner_tone",
            field=models.CharField(
                choices=[
                    ("info", "Information"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("primary", "Primary"),
                ],
                default="primary",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="PubmedArticleUserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("starred_at", models.DateTimeField(blank=True, null=True)),
                ("recommended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="backend.pubmedarticle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pubmed_article_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "article"),
                        name="uniq_pubmed_article_user_state",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchedJournalArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("publication_month", models.DateField(blank=True, null=True)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_links",
                        to="backend.pubmedarticle",
                    ),
                ),
                (
                    "watched_journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_articles",
                        to="backend.watchedjournal",
                    ),
                ),
            ],
            options={
                "ordering": ("-publication_month", "-last_seen_at"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("watched_journal", "article"),
                        name="uniq_watched_journal_article",
                    )
                ],
            },
        ),
    ]
