# Generated by Django 6.0.3 on 2026-03-30 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0032_backendpreference_frontend_banner_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pubmedarticleuserstate",
            index=models.Index(
                fields=["article", "recommended_at"],
                name="backend_paus_article_rec_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pubmedarticleuserstate",
            index=models.Index(
                fields=["user", "starred_at"], name="backend_paus_user_star_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchedjournalarticle",
            index=models.Index(
                fields=["publication_month"], name="backend_wja_pub_month_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="watchedjournalarticle",
            index=models.Index(
                fields=["watched_journal", "publication_month"],
                name="backend_wja_journal_month_idx",
            ),
        ),
    ]
