# Generated by Django 6.0.3 on 2026-04-01 06:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_schedule_pubmed_journal_cache_refresh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribercsv',
            options={'permissions': [('manage_subscriber_csv', 'Can create and edit CSV subscriber lists'), ('send_newsletters', 'Can send out newsletters to all subscribers'), ('view_newsletter_stats', 'Can view newsletter open and click statistics'), ('view_site_analytics', 'Can view site analytics (overview, content, traffic, search, journals)')], 'verbose_name': 'Subscriber list CSV'},
        ),
        migrations.AddField(
            model_name='pubmedarticleuserstate',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pubmedarticleuserstate',
            index=models.Index(fields=['user', 'read_at'], name='backend_paus_user_read_idx'),
        ),
    ]
