# Generated by Django 6.0.3 on 2026-04-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_add_read_at_to_pubmedarticleuserstate'),
        ('submissions', '0043_populate_article_pubmed_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticle',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='citation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='submissions.journal'),
        ),
        migrations.AddField(
            model_name='pubmedarticle',
            name='tags_string',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='pubmedarticle',
            name='pmid',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='pubmedarticle',
            index=models.Index(fields=['pmid'], name='backend_pa_pmid_idx'),
        ),
    ]
