# Generated by Django 6.0.3 on 2026-04-01 12:49
import datetime

from django.db import migrations


def migrate_article_data(apps, schema_editor):
    """Copy submissions.Article data into backend.PubmedArticle.

    For Articles already linked via pubmed_article FK: copy editorial fields.
    For unlinked Articles: create new PubmedArticle rows.
    Stores the mapping (old Article PK → PubmedArticle PK) in a temp table-like
    approach using the pubmed_article FK itself, so subsequent FK migrations can
    look it up.
    """
    Article = apps.get_model("submissions", "Article")
    PubmedArticle = apps.get_model("backend", "PubmedArticle")

    for article in Article.objects.all():
        if article.pubmed_article_id:
            # Linked: copy editorial fields to existing PubmedArticle
            pa = PubmedArticle.objects.get(pk=article.pubmed_article_id)
            pa.tags_string = article.tags_string or ""
            pa.journal_id = article.journal_id
            pa.citation = article.citation or ""
            pa.active = article.active
            pa.save(update_fields=["tags_string", "journal_id", "citation", "active"])
        else:
            # Unlinked: create new PubmedArticle from Article data
            pub_date = datetime.date(article.year, 1, 1) if article.year else None
            pa = PubmedArticle.objects.create(
                pmid=None,
                title=article.name,
                journal_id=article.journal_id,
                citation=article.citation or "",
                article_url=article.url or "",
                tags_string=article.tags_string or "",
                active=article.active,
                publication_date=pub_date,
                publication_month=pub_date,
            )
            # Store the link so FK migrations can find it
            article.pubmed_article_id = pa.pk
            article.save(update_fields=["pubmed_article_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0036_add_editorial_fields_to_pubmedarticle"),
        ("submissions", "0043_populate_article_pubmed_links"),
    ]

    operations = [
        migrations.RunPython(migrate_article_data, migrations.RunPython.noop),
    ]
