# Generated by Django 6.0.3 on 2026-04-01 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_update_pubmed_cache_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticle',
            name='recommendation_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
