# Generated by Django 6.0.3 on 2026-04-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_add_recommendation_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedjournal',
            name='visible_on_frontend',
            field=models.BooleanField(default=True),
        ),
    ]
