# Generated by Django 6.0.3 on 2026-04-02 03:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_add_chief_editor_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('task_type', models.CharField(choices=[('cache_refresh', 'Cache refresh'), ('batch_import', 'Batch import'), ('batch_push', 'Batch push')], max_length=24)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=16)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('journal_count', models.PositiveIntegerField(default=0)),
                ('articles_created', models.PositiveIntegerField(default=0)),
                ('articles_touched', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
