# Generated by Django 6.0.3 on 2026-04-02 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_add_fetch_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedarticleuserstate',
            name='full_text_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pubmedarticleuserstate',
            index=models.Index(fields=['user', 'full_text_clicked_at'], name='backend_paus_user_ftclick_idx'),
        ),
    ]
