# Generated by Django 6.0.3 on 2026-04-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_pubmedarticleuserstate_full_text_clicked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedjournal',
            name='source',
            field=models.CharField(choices=[('pubmed', 'PubMed'), ('crossref', 'CrossRef')], default='pubmed', max_length=16),
        ),
    ]
