# Generated by Django 6.0.3 on 2026-04-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_watchedjournal_source_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedjournal',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom display name; falls back to name if blank', max_length=255),
        ),
        migrations.AddField(
            model_name='watchedjournal',
            name='iso_abbreviation',
            field=models.CharField(blank=True, help_text='ISO journal abbreviation for article matching', max_length=255),
        ),
        migrations.AddField(
            model_name='watchedjournal',
            name='medline_ta',
            field=models.CharField(blank=True, help_text='MEDLINE title abbreviation — most reliable PubMed search identifier', max_length=255, verbose_name='MedlineTA'),
        ),
        migrations.AddField(
            model_name='watchedjournal',
            name='nlm_id',
            field=models.CharField(blank=True, help_text='NLM catalog unique identifier', max_length=64, verbose_name='NLM ID'),
        ),
    ]
