# Generated by Django 6.0.3 on 2026-04-18 12:00

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0047_schedule_tag_clusters_task"),
        ("submissions", "0052_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emailthread",
            index=models.Index(fields=["-last_message_at"], name="backend_email_lastmsg_idx"),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["external_address"],
                name="backend_email_extaddr_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="emailthread",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["subject"],
                name="backend_email_subject_trgm",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
