# Generated by Django 6.0.4 on 2026-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_backfill_article_journal_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribercsv',
            name='task_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscribercsv',
            name='task_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='idle', max_length=16),
        ),
        migrations.AddField(
            model_name='subscribercsv',
            name='task_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
