# Generated by Django 6.0.4 on 2026-09-04 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_pubmedimportbatch_last_pubmed_fetched_at_and_more'),
        ('submissions', '0056_backfill_review_publish_date_from_first_open'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlankaProjectSetupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('project_name', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('background_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setup_jobs', to='backend.plankaboardbackgroundasset')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planka_setup_job', to='submissions.issue')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planka Project Setup Job',
                'verbose_name_plural': 'Planka Project Setup Jobs',
            },
        ),
    ]
