# Generated by Django 6.0.4 on 2026-09-04 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_plankaprojectsetupjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubmedArticleVisitorRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('session_key', models.CharField(max_length=64)),
                ('visitor_id', models.CharField(blank=True, max_length=64)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_recommendations', to='backend.pubmedarticle')),
            ],
            options={
                'indexes': [models.Index(fields=['session_key'], name='backend_pavr_session_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'session_key'), name='uniq_pubmed_article_visitor_rec')],
            },
        ),
    ]
