#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

exec /usr/local/bin/gunicorn config.wsgi \
  --bind "0.0.0.0:${GUNICORN_PORT:-5000}" \
  --chdir=/app \
  --workers "${WEB_CONCURRENCY:-2}" \
  --threads "${GUNICORN_THREADS:-4}" \
  --worker-class "${GUNICORN_WORKER_CLASS:-gthread}" \
  --worker-tmp-dir /dev/shm
