# Generated by Django 4.1.9 on 2023-06-07 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeatureArticle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("override_main", models.BooleanField(default=False)),
                ("override_card", models.BooleanField(default=False)),
                ("publication_ready", models.BooleanField(default=False)),
                ("card_features", models.ManyToManyField(related_name="card_features", to="layout.featurearticle")),
                ("issue", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="submissions.issue")),
                (
                    "main_feature",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"),
                ),
            ],
        ),
    ]
