# Generated by Django 4.1.9 on 2023-06-07 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0002_featurearticle_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="card_features",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="card_features", to="layout.featurearticle"
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="main_feature",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="layout.featurearticle"
            ),
        ),
    ]
