# Generated by Django 4.1.9 on 2023-06-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("layout", "0004_homepage_created_homepage_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="card_features",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="override_card",
        ),
        migrations.AddField(
            model_name="featurearticle",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
