# Generated by Django 4.1.9 on 2023-06-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0006_alter_hit_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
