# Generated by Django 4.1.9 on 2023-06-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0007_journal_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
