# Generated by Django 4.1.9 on 2023-06-22 10:05

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0010_author_alter_review_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
