# Generated by Django 4.1.9 on 2023-06-22 10:39

import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0011_review_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="citation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
