# Generated by Django 4.1.9 on 2023-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0012_article_citation_alter_review_search_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="slug",
            field=models.SlugField(blank=True, max_length=50, unique=True),
        ),
    ]
