# Generated by Django 4.1.9 on 2023-06-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0013_alter_review_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
