# Generated by Django 4.1.9 on 2023-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0015_review_feature_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feature_image_height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="feature_image_width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
