# Generated by Django 4.1.9 on 2023-06-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0016_review_feature_image_height_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="feature_image_hash",
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
    ]
