# Generated by Django 4.1.9 on 2023-06-29 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0017_review_feature_image_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="feature_image_hash",
        ),
    ]
