# Generated by Django 4.1.9 on 2023-07-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0018_remove_review_feature_image_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="feature_image_height",
        ),
        migrations.RemoveField(
            model_name="review",
            name="feature_image_width",
        ),
        migrations.AlterField(
            model_name="review",
            name="feature_image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/review/"),
        ),
    ]
