# Generated by Django 4.1.9 on 2023-07-03 07:59

from django.db import migrations, models
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0019_remove_review_feature_image_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="feature_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
            ),
        ),
    ]
