# Generated by Django 4.1.9 on 2023-07-08 06:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0021_issue_issue_detail_page"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="main_feature",
        ),
    ]
