# Generated by Django 4.1.9 on 2023-07-14 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0022_remove_issue_main_feature"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("url", models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="author",
            name="title",
            field=models.CharField(default="Dr", max_length=255),
        ),
        migrations.AddField(
            model_name="author",
            name="health_services",
            field=models.ManyToManyField(to="submissions.healthservice"),
        ),
    ]
