# Generated by Django 4.1.9 on 2023-07-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0023_healthservice_author_title_author_health_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
