# Generated by Django 4.1.9 on 2023-07-16 06:29

from django.db import migrations, models
import django.db.models.deletion
import spanza_journal_watch.utils.modelmethods


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0026_healthservice_logo_healthservice_logo_authorised_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=spanza_journal_watch.utils.modelmethods.name_image
            ),
        ),
        migrations.AddField(
            model_name="author",
            name="show_profile_image",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="submissions.author",
            ),
        ),
    ]
