# Generated by Django 4.1.9 on 2023-07-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0027_author_profile_image_author_show_profile_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="health_services",
            field=models.ManyToManyField(blank=True, related_name="authors", to="submissions.healthservice"),
        ),
    ]
