# Generated by Django 4.1.9 on 2023-07-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0028_alter_author_health_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
