# Generated by Django 4.1.9 on 2023-07-29 00:56

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import BtreeGinExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0028_alter_author_health_services"),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name="article",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="gin_trgm_idx", opclasses=("gin_trgm_ops",)
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=django.contrib.postgres.indexes.GinIndex(fields=["search_vector"], name="submissions_body_708dad_gin"),
        ),
    ]
