# Generated by Django 4.2.5 on 2024-02-08 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0031_alter_hit_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="year",
            field=models.IntegerField(
                default=2024,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2025),
                ],
            ),
        ),
    ]
