# Generated by Django 4.2.5 on 2025-05-07 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0032_alter_article_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="year",
            field=models.IntegerField(
                default=2025,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2026),
                ],
            ),
        ),
    ]
