# Generated by Django 4.2.5 on 2025-05-07 01:53

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0033_alter_article_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="body",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
