# Generated by Django 4.2.5 on 2026-01-21 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0034_alter_review_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="year",
            field=models.IntegerField(
                default=2026,
                validators=[
                    django.core.validators.MinValueValidator(1900),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
    ]
