# Generated by Django 4.2.5 on 2026-03-15 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0035_alter_article_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="issue_detail_page",
        ),
    ]
