# Generated by Django 4.2.5 on 2026-03-15 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submissions", "0036_remove_issue_issue_detail_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={
                "permissions": [
                    ("manage_issue_builder", "Can create and publish issue bundles in backend issue builder")
                ]
            },
        ),
    ]
