# Generated by Django 6.0.3 on 2026-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0040_issue_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Email used to match this author to invited contributors",
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
    ]
