# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_add_read_at_to_pubmedarticleuserstate'),
        ('submissions', '0041_author_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubmed_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editorial_articles', to='backend.pubmedarticle'),
        ),
    ]
