# Generated by Django 6.0.3 on 2026-04-01 12:16

import re

from django.db import migrations

DOI_RE = re.compile(r"10\.\d{4,9}/[^\s]+")


def populate_links(apps, schema_editor):
    Article = apps.get_model("submissions", "Article")
    PubmedArticle = apps.get_model("backend", "PubmedArticle")

    for article in Article.objects.filter(pubmed_article__isnull=True):
        # Try DOI extracted from URL
        if article.url:
            m = DOI_RE.search(article.url)
            if m:
                doi = m.group(0).lower().rstrip(".")
                try:
                    pa = PubmedArticle.objects.get(doi=doi)
                    article.pubmed_article = pa
                    article.save(update_fields=["pubmed_article"])
                    continue
                except PubmedArticle.DoesNotExist:
                    pass

        # Try title prefix match (first 60 chars before colon)
        title_prefix = article.name.split(":")[0].strip()[:60]
        if len(title_prefix) > 20:
            matches = PubmedArticle.objects.filter(title__icontains=title_prefix)
            if matches.count() == 1:
                article.pubmed_article = matches.first()
                article.save(update_fields=["pubmed_article"])


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0042_add_article_pubmed_article_fk"),
    ]

    operations = [
        migrations.RunPython(populate_links, migrations.RunPython.noop),
    ]
