# Generated by Django 6.0.3 on 2026-04-01

import django.db.models.deletion
from django.db import migrations, models


def migrate_review_fk(apps, schema_editor):
    """Copy Review.article → Review.new_article via the Article.pubmed_article link."""
    Review = apps.get_model("submissions", "Review")
    for review in Review.objects.select_related("article").all():
        if review.article and review.article.pubmed_article_id:
            review.new_article_id = review.article.pubmed_article_id
            review.save(update_fields=["new_article_id"])


def migrate_comment_fk(apps, schema_editor):
    """Copy Comment.article → Comment.new_article via the Article.pubmed_article link."""
    Comment = apps.get_model("submissions", "Comment")
    for comment in Comment.objects.select_related("article").all():
        if comment.article and comment.article.pubmed_article_id:
            comment.new_article_id = comment.article.pubmed_article_id
            comment.save(update_fields=["new_article_id"])


def migrate_tag_m2m(apps, schema_editor):
    """Copy Tag ↔ Article M2M to Tag ↔ PubmedArticle via Article.pubmed_article."""
    Tag = apps.get_model("submissions", "Tag")
    for tag in Tag.objects.prefetch_related("articles").all():
        for article in tag.articles.all():
            if article.pubmed_article_id:
                tag.new_articles.add(article.pubmed_article_id)


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0043_populate_article_pubmed_links"),
        ("backend", "0037_migrate_article_data_to_pubmedarticle"),
    ]

    operations = [
        # --- Step 1: Add new FK/M2M fields pointing to PubmedArticle ---
        migrations.AddField(
            model_name="review",
            name="new_article",
            field=models.ForeignKey(
                to="backend.PubmedArticle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="new_article",
            field=models.ForeignKey(
                to="backend.PubmedArticle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                null=True,
                blank=True,
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="new_articles",
            field=models.ManyToManyField(
                to="backend.PubmedArticle",
                related_name="+",
                blank=True,
            ),
        ),
        # --- Step 2: Data-migrate values ---
        migrations.RunPython(migrate_review_fk, migrations.RunPython.noop),
        migrations.RunPython(migrate_comment_fk, migrations.RunPython.noop),
        migrations.RunPython(migrate_tag_m2m, migrations.RunPython.noop),
        # --- Step 3: Remove old fields ---
        migrations.RemoveField(model_name="review", name="article"),
        migrations.RemoveField(model_name="comment", name="article"),
        migrations.RemoveField(model_name="tag", name="articles"),
        # --- Step 4: Rename new fields to original names ---
        migrations.RenameField(model_name="review", old_name="new_article", new_name="article"),
        migrations.RenameField(model_name="comment", old_name="new_article", new_name="article"),
        migrations.RenameField(model_name="tag", old_name="new_articles", new_name="articles"),
        # --- Step 5: Make Review.article non-nullable + set related names ---
        migrations.AlterField(
            model_name="review",
            name="article",
            field=models.ForeignKey(
                to="backend.PubmedArticle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="article",
            field=models.ForeignKey(
                to="backend.PubmedArticle",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="articles",
            field=models.ManyToManyField(
                to="backend.PubmedArticle",
                related_name="tags",
            ),
        ),
    ]
