# Generated by Django 6.0.3 on 2026-04-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0044_repoint_fks_to_pubmedarticle'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='article',
            name='gin_trgm_idx',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
