# Generated by Django 6.0.3 on 2026-04-03 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0046_add_can_recommend_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='curated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tag',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MeshTagMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesh_term', models.CharField(db_index=True, max_length=255, unique=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesh_mappings', to='submissions.tag')),
            ],
            options={
                'ordering': ('mesh_term',),
            },
        ),
    ]
