# Generated by Django 6.0.3 on 2026-04-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0048_populate_curated_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='collections', to='submissions.tag')),
            ],
            options={
                'ordering': ('display_order', '-created'),
            },
        ),
    ]
