# Generated by Django 6.0.3 on 2026-04-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0049_curatedcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedcollection',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='collections', to='submissions.review'),
        ),
    ]
