# Generated by Django 6.0.3 on 2026-04-05 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0050_curatedcollection_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'permissions': [('manage_issue_builder', 'Can create and publish issue bundles in backend issue builder'), ('chief_editor', 'Can edit reviews, publish issues, and access chief editor functions'), ('regional_coordinator', 'Can edit assigned issues and reviews; cannot publish or manage newsletter'), ('can_recommend', 'Can recommend articles for review'), ('invited_contributor', 'Invited contributor — can access editorial tools and Planka')]},
        ),
    ]
