# Generated by Django 6.0.3 on 2026-04-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_schedule_tag_clusters_task'),
        ('submissions', '0051_add_invited_contributor_permission'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['active', '-date'], name='submissions_active_c9c346_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['active', '-created'], name='submissions_active_162926_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['active', 'curated'], name='submissions_active_2eafaf_idx'),
        ),
    ]
