# Generated by Django 6.0.3 on 2026-04-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0052_add_performance_indexes"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["active", "-publish_date"], name="submissions_active_91ec4a_idx"),
        ),
    ]
