# Generated by Django 6.0.4 on 2026-07-01 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0054_tag_article_composite_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueSlugRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('old_slug', models.SlugField(max_length=255, unique=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slug_redirects', to='submissions.issue')),
            ],
            options={
                'verbose_name': 'Issue slug redirect',
            },
        ),
    ]
