# Generated by Django 6.0.4 on 2026-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0056_backfill_review_publish_date_from_first_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='bottom_line',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='editorial_headline',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
