# Generated by Django 6.0.4 on 2026-09-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0057_review_editorial_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='draft_bottom_line',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='draft_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='draft_headline',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
