# Generated by Django 4.1.9 on 2023-08-31 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("newsletter", "0009_newsletter_email_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("object_id", models.PositiveIntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
            ],
            options={
                "ordering": ("-timestamp",),
            },
        ),
        migrations.CreateModel(
            name="NewsletterOpen",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_address", models.EmailField(max_length=254)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="newsletter.newsletter"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewsletterClick",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email_address", models.EmailField(max_length=254)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "newsletter",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="newsletter.newsletter"),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="pageview",
            index=models.Index(fields=["content_type", "object_id"], name="analytics_p_content_73920a_idx"),
        ),
    ]
