# Generated by Django 4.1.9 on 2023-09-01 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("newsletter", "0009_newsletter_email_token"),
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterclick",
            name="subscriber",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="newsletter.subscriber"
            ),
        ),
        migrations.AddField(
            model_name="newsletteropen",
            name="subscriber",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="newsletter.subscriber"
            ),
        ),
        migrations.AddField(
            model_name="pageview",
            name="subscriber",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="newsletter.subscriber"
            ),
        ),
    ]
