# Generated by Django 4.1.9 on 2023-09-01 02:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_newsletterclick_subscriber_newsletteropen_subscriber_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterclick",
            name="email_address",
        ),
        migrations.RemoveField(
            model_name="newsletteropen",
            name="email_address",
        ),
    ]
