# Generated by Django 4.2.5 on 2026-03-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0004_alter_newsletterclick_subscriber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletterclick",
            name="automated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsletterclick",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="newsletteropen",
            name="automated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="newsletteropen",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
    ]
