# Generated by Django 6.0.3 on 2026-03-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_pageview_human_confidence_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_t_64745b_idx',
            old_name='analytics_a_event_t_1af153_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_content_ac669b_idx',
            old_name='analytics_a_content_49598d_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_source_5ad05a_idx',
            old_name='analytics_a_source_f2dc93_idx',
        ),
    ]
