# Generated by Django 6.0.3 on 2026-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_rename_analytics_a_event_t_1af153_idx_analytics_a_event_t_64745b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='referrer_category',
            field=models.CharField(blank=True, choices=[('newsletter', 'Newsletter'), ('search', 'Search engine'), ('social', 'Social media'), ('direct', 'Direct'), ('internal', 'Internal'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='visitor_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer_category',
            field=models.CharField(blank=True, choices=[('newsletter', 'Newsletter'), ('search', 'Search engine'), ('social', 'Social media'), ('direct', 'Direct'), ('internal', 'Internal'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='pageview',
            name='visitor_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('review_open', 'Review open'), ('review_engaged', 'Review engaged'), ('review_full_text_click', 'Review full text click'), ('review_share_copy_link', 'Review shared via copy link'), ('review_share_email', 'Review shared via email'), ('review_share_native', 'Review shared via native share'), ('review_share_bluesky', 'Review shared via Bluesky'), ('review_share_x', 'Review shared via X'), ('review_share_facebook', 'Review shared via Facebook'), ('search', 'Search performed'), ('search_result_click', 'Search result clicked'), ('page_visit', 'Page visit'), ('journal_browser_visit', 'Journal browser visit'), ('journal_article_interact', 'Journal article interaction')], max_length=48),
        ),
    ]
