# Generated by Django 6.0.3 on 2026-04-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0010_analytics_visitor_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='js_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='landing_page',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='referrer_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='session_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='newsletterclick',
            name='destination_url',
            field=models.URLField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='newsletterclick',
            name='human_confidence',
            field=models.CharField(choices=[('suspected_automated', 'Suspected automated'), ('probable_human', 'Probable human'), ('known_subscriber_human', 'Known subscriber human')], default='probable_human', max_length=32),
        ),
        migrations.AddField(
            model_name='newsletteropen',
            name='human_confidence',
            field=models.CharField(choices=[('suspected_automated', 'Suspected automated'), ('probable_human', 'Probable human'), ('known_subscriber_human', 'Known subscriber human')], default='probable_human', max_length=32),
        ),
        migrations.AddField(
            model_name='pageview',
            name='referrer_domain',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
