# Generated by Django 6.0.3 on 2026-04-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0012_alter_analyticsevent_event_type'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('newsletter', '0015_add_subscriber_user_fk'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['session_key'], name='analytics_a_session_598c8c_idx'),
        ),
    ]
