# Generated by Django 6.0.3 on 2026-04-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0013_session_key_index"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
