# Generated by Django 6.0.4 on 2026-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0015_schedule_downgrade_singleton_visitors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedRequestCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('review_open', 'Review open'), ('review_engaged', 'Review engaged'), ('review_full_text_click', 'Review full text click'), ('review_share_copy_link', 'Review shared via copy link'), ('review_share_email', 'Review shared via email'), ('review_share_native', 'Review shared via native share'), ('review_share_bluesky', 'Review shared via Bluesky'), ('review_share_x', 'Review shared via X'), ('review_share_facebook', 'Review shared via Facebook'), ('search', 'Search performed'), ('search_result_click', 'Search result clicked'), ('page_visit', 'Page visit'), ('journal_browser_visit', 'Journal browser visit'), ('journal_article_interact', 'Journal article interaction'), ('journal_full_text_click', 'Journal full text click'), ('journal_star', 'Journal article starred'), ('journal_select', 'Journal selected')], max_length=48)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-date', 'event_type'),
                'indexes': [models.Index(fields=['date'], name='analytics_a_date_0b91a8_idx')],
                'unique_together': {('date', 'event_type')},
            },
        ),
    ]
