# Generated by Django 6.0.4 on 2026-04-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0018_schedule_no_js_burst_downgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('review_open', 'Review open'), ('review_engaged', 'Review engaged'), ('review_full_text_click', 'Review full text click'), ('review_related_click', 'Review related-link click'), ('review_share_copy_link', 'Review shared via copy link'), ('review_share_email', 'Review shared via email'), ('review_share_native', 'Review shared via native share'), ('review_share_bluesky', 'Review shared via Bluesky'), ('review_share_x', 'Review shared via X'), ('review_share_facebook', 'Review shared via Facebook'), ('search', 'Search performed'), ('search_result_click', 'Search result clicked'), ('page_visit', 'Page visit'), ('journal_browser_visit', 'Journal browser visit'), ('journal_article_interact', 'Journal article interaction'), ('journal_full_text_click', 'Journal full text click'), ('journal_star', 'Journal article starred'), ('journal_select', 'Journal selected')], max_length=48),
        ),
        migrations.AlterField(
            model_name='automatedrequestcount',
            name='event_type',
            field=models.CharField(choices=[('review_open', 'Review open'), ('review_engaged', 'Review engaged'), ('review_full_text_click', 'Review full text click'), ('review_related_click', 'Review related-link click'), ('review_share_copy_link', 'Review shared via copy link'), ('review_share_email', 'Review shared via email'), ('review_share_native', 'Review shared via native share'), ('review_share_bluesky', 'Review shared via Bluesky'), ('review_share_x', 'Review shared via X'), ('review_share_facebook', 'Review shared via Facebook'), ('search', 'Search performed'), ('search_result_click', 'Search result clicked'), ('page_visit', 'Page visit'), ('journal_browser_visit', 'Journal browser visit'), ('journal_article_interact', 'Journal article interaction'), ('journal_full_text_click', 'Journal full text click'), ('journal_star', 'Journal article starred'), ('journal_select', 'Journal selected')], max_length=48),
        ),
    ]
