# Generated by Django 6.0.4

from django.db import migrations, models


EVENT_TYPE_CHOICES = [
    ("review_open", "Review open"),
    ("review_engaged", "Review engaged"),
    ("review_full_text_click", "Review full text click"),
    ("review_related_click", "Review related-link click"),
    ("review_share_copy_link", "Review shared via copy link"),
    ("review_share_email", "Review shared via email"),
    ("review_share_native", "Review shared via native share"),
    ("review_share_bluesky", "Review shared via Bluesky"),
    ("review_share_x", "Review shared via X"),
    ("review_share_facebook", "Review shared via Facebook"),
    ("search", "Search performed"),
    ("search_result_click", "Search result clicked"),
    ("page_visit", "Page visit"),
    ("journal_browser_visit", "Journal browser visit"),
    ("journal_article_interact", "Journal article interaction"),
    ("journal_full_text_click", "Journal full text click"),
    ("journal_star", "Journal article starred"),
    ("journal_recommend", "Journal article recommended"),
    ("journal_mark_read", "Journal article marked read"),
    ("journal_archive", "Journal article archived"),
    ("journal_search", "Journal browser search"),
    ("journal_select", "Journal selected"),
    ("newsletter_subscribe", "Newsletter subscribe"),
    ("cpd_tracking_toggle", "CPD tracking toggled"),
]


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0019_alter_analyticsevent_event_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analyticsevent",
            name="event_type",
            field=models.CharField(choices=EVENT_TYPE_CHOICES, max_length=48),
        ),
        migrations.AlterField(
            model_name="automatedrequestcount",
            name="event_type",
            field=models.CharField(choices=EVENT_TYPE_CHOICES, max_length=48),
        ),
    ]
