# Generated by Django 6.0.4 on 2026-06-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0022_schedule_prune_automated_events'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automatedrequestcount',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='automatedrequestcount',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterUniqueTogether(
            name='automatedrequestcount',
            unique_together={('date', 'event_type', 'reason')},
        ),
    ]
