#!/usr/bin/env bash
# =============================================================================
# ops/gen-env.sh — Generate a production .env with all secrets pre-filled.
#
# Usage:
#   bash ops/gen-env.sh            # writes .env in the project root
#   bash ops/gen-env.sh --dry-run  # print to stdout instead
#
# The script prompts for the four values that come from outside:
#   DOMAIN, PLANKA_DOMAIN, ADMIN_EMAIL, DOCKERHUB_NAMESPACE
#
# Everything else (keys, passwords, RSA key) is generated automatically.
# The OIDC RSA key generation (openssl genrsa 4096) takes ~5 seconds.
# =============================================================================
set -euo pipefail

DRY_RUN=false
[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
gen_token() { python3 -c "import secrets; print(secrets.token_urlsafe($1))"; }
gen_hex()   { openssl rand -hex "$1"; }
prompt() {
    local var="$1" label="$2" default="${3:-}"
    local value=""
    if [[ -n "$default" ]]; then
        read -rp "  ${label} [${default}]: " value
        value="${value:-$default}"
    else
        while [[ -z "$value" ]]; do
            read -rp "  ${label}: " value
        done
    fi
    printf -v "$var" '%s' "$value"
}

# ---------------------------------------------------------------------------
# Safety check
# ---------------------------------------------------------------------------
OUTFILE="${PWD}/.env"
if [[ "$DRY_RUN" == false && -f "$OUTFILE" ]]; then
    echo ""
    echo "  WARNING: $OUTFILE already exists."
    read -rp "  Overwrite? [y/N]: " yn
    [[ "${yn,,}" == "y" ]] || { echo "Aborted."; exit 0; }
fi

# ---------------------------------------------------------------------------
# Prompts
# ---------------------------------------------------------------------------
echo ""
echo "=== Journal Watch — production environment setup ==="
echo ""
echo "Press Enter to accept the default shown in [brackets]."
echo ""

prompt DOMAIN           "Primary domain (e.g. journalwatch.org.au)"
prompt PLANKA_DOMAIN    "Planka subdomain"                          "planka.${DOMAIN}"
prompt ADMIN_EMAIL      "Admin email address"                       "admin@${DOMAIN}"
prompt DOCKERHUB_NS     "Docker Hub namespace"

echo ""
echo "Generating secrets..."

DJANGO_SECRET_KEY="$(gen_token 64)"
POSTGRES_USER="jw_$(gen_token 8 | tr -dc 'a-z0-9' | head -c 8)"
POSTGRES_PASSWORD="$(gen_token 24)"
WEBHOOK_SECRET="$(gen_token 24)"
FLOWER_USER="flower"
FLOWER_PASSWORD="$(gen_token 24)"
OIDC_CLIENT_SECRET="$(gen_hex 32)"
PLANKA_SECRET_KEY="$(gen_hex 32)"
DJANGO_ADMIN_PATH="$(gen_token 12 | tr -dc 'a-zA-Z0-9' | head -c 12)"
DEFAULT_ADMIN_PASSWORD="$(gen_token 16)"

echo "  Generating OIDC RSA private key (this takes a few seconds)..."
OIDC_RSA_KEY="$(openssl genrsa 4096 2>/dev/null | base64 | tr -d '\n')"

echo "  Done."
echo ""

# ---------------------------------------------------------------------------
# Build the env file
# ---------------------------------------------------------------------------
ENV_CONTENT="# =============================================================================
# SPANZA Journal Watch — production environment
# Generated by ops/gen-env.sh on $(date -u '+%Y-%m-%d %H:%M UTC')
#
# Edit AWS credentials, SES settings, and Sentry DSN before deploying.
# =============================================================================


# =============================================================================
# Docker Hub
# =============================================================================

DOCKERHUB_NAMESPACE=${DOCKERHUB_NS}
APP_TAG=latest


# =============================================================================
# Django
# =============================================================================

DJANGO_SETTINGS_MODULE=config.settings.production
DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
DJANGO_ADMIN_URL=${DJANGO_ADMIN_PATH}/
DJANGO_ALLOWED_HOSTS=[\".${DOMAIN}\"]

# Set False when TLS is terminated upstream (nginx, Caddy, ALB, etc.)
DJANGO_SECURE_SSL_REDIRECT=False

DJANGO_SERVER_EMAIL=Journal Watch <noreply@${DOMAIN}>
DJANGO_DEFAULT_FROM_EMAIL=Journal Watch <noreply@${DOMAIN}>

DJANGO_ACCOUNT_ALLOW_REGISTRATION=True

# Gunicorn workers: 2 × CPU cores + 1
WEB_CONCURRENCY=3


# =============================================================================
# PostgreSQL (Django database)
# =============================================================================

POSTGRES_DB=spanza_journal_watch
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}


# =============================================================================
# AWS (S3 media storage + SES email)
# These values are also passed to Planka for S3 attachment storage —
# no need to duplicate them; see compose.prod.example.yml.
# =============================================================================

DJANGO_AWS_ACCESS_KEY_ID=REPLACE_WITH_IAM_ACCESS_KEY
DJANGO_AWS_SECRET_ACCESS_KEY=REPLACE_WITH_IAM_SECRET_KEY
DJANGO_AWS_STORAGE_BUCKET_NAME=REPLACE_WITH_BUCKET_NAME
DJANGO_AWS_S3_REGION_NAME=ap-southeast-2
DJANGO_AWS_DEFAULT_REGION=ap-southeast-2


# =============================================================================
# Amazon SES (transactional email)
# =============================================================================

# SNS webhook signing secret — must match the value registered in SES/SNS
WEBHOOK_SECRET=${WEBHOOK_SECRET}
DJANGO_ANYMAIL_INBOUND_S3_OBJECT_PREFIX=email


# =============================================================================
# Celery / Flower
# =============================================================================

CELERY_FLOWER_USER=${FLOWER_USER}
CELERY_FLOWER_PASSWORD=${FLOWER_PASSWORD}


# =============================================================================
# Sentry (optional — leave blank to disable)
# =============================================================================

SENTRY_DSN=
SENTRY_TRACES_SAMPLE_RATE=0.1
SENTRY_PROFILES_SAMPLE_RATE=0.1


# =============================================================================
# OIDC — Django as OAuth2/OIDC provider for Planka
# =============================================================================

# Base64-encoded RSA private key (generated by this script)
OIDC_RSA_PRIVATE_KEY=${OIDC_RSA_KEY}

# Public URL of the Django OIDC endpoint
OIDC_ISS_ENDPOINT=https://${DOMAIN}/o


# =============================================================================
# Planka integration (Django → Planka API)
# =============================================================================

PLANKA_EXTERNAL_URL=https://${PLANKA_DOMAIN}
PLANKA_ADMIN_EMAIL=${ADMIN_EMAIL}


# =============================================================================
# Planka application
# =============================================================================

BASE_URL=https://${PLANKA_DOMAIN}
DATABASE_URL=postgresql://postgres@planka_postgres/planka
SECRET_KEY=${PLANKA_SECRET_KEY}
USER_TERMS_OF_SERVICE_VERSION=1

# OIDC: run 'manage.py setup_planka_oidc' once after first boot.
# OIDC_ISSUER and DEFAULT_ADMIN_EMAIL are set automatically by compose from
# the vars above — no need to duplicate them here.
OIDC_CLIENT_ID=planka-production
OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
OIDC_USE_DEFAULT_RESPONSE_MODE=true
OIDC_SCOPES=openid email profile
OIDC_EMAIL_ATTRIBUTE=email
OIDC_NAME_ATTRIBUTE=name
OIDC_IGNORE_USERNAME=true
OIDC_IGNORE_ROLES=true
# Enable AFTER running setup_planka_api_key from the backend settings UI.
# Uncomment and restart Planka to enforce SSO-only login.
# OIDC_ENFORCED=true

# Admin bootstrap — used only by 'manage.py setup_planka_api_key'
DEFAULT_ADMIN_NAME=Journal Watch Admin
DEFAULT_ADMIN_USERNAME=admin
# Remove this after the Planka API key has been set up (see: make planka-setup)
DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}


# =============================================================================
# Planka — S3 object storage
# Uses a SEPARATE IAM user and a SEPARATE bucket for Planka.
# See docs/operations/aws-setup.md for the required IAM policy.
# =============================================================================

PLANKA_S3_BUCKET=REPLACE_WITH_PLANKA_BUCKET_NAME
PLANKA_S3_ACCESS_KEY_ID=REPLACE_WITH_PLANKA_IAM_ACCESS_KEY
PLANKA_S3_SECRET_ACCESS_KEY=REPLACE_WITH_PLANKA_IAM_SECRET_KEY
PLANKA_S3_REGION=${DJANGO_AWS_S3_REGION_NAME:-ap-southeast-2}
"

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------
if [[ "$DRY_RUN" == true ]]; then
    echo "$ENV_CONTENT"
else
    echo "$ENV_CONTENT" > "$OUTFILE"
    chmod 600 "$OUTFILE"
    echo "Written to: $OUTFILE"
    echo ""
fi

# ---------------------------------------------------------------------------
# Restic env pre-fill hint
# ---------------------------------------------------------------------------
RESTIC_HINT="# Pre-filled from gen-env.sh — add AWS and SMTP credentials before use.
RESTIC_REPOSITORY=s3:s3.amazonaws.com/REPLACE_WITH_BUCKET_NAME/backups
RESTIC_PASSWORD=$(gen_token 32)

AWS_ACCESS_KEY_ID=REPLACE_WITH_IAM_ACCESS_KEY
AWS_SECRET_ACCESS_KEY=REPLACE_WITH_IAM_SECRET_KEY
AWS_DEFAULT_REGION=ap-southeast-2

POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
POSTGRES_DB=spanza_journal_watch
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

PLANKA_DB_HOST=127.0.0.1
PLANKA_DB_PORT=5433

KEEP_DAILY=7
KEEP_WEEKLY=4
KEEP_MONTHLY=6

ALERT_EMAIL=${ADMIN_EMAIL}
SMTP_HOST=email-smtp.ap-southeast-2.amazonaws.com
SMTP_PORT=587
SMTP_TLS=on
SMTP_USER=REPLACE_WITH_SES_SMTP_USER
SMTP_PASSWORD=REPLACE_WITH_SES_SMTP_PASSWORD
SMTP_FROM=backup@${DOMAIN}
NOTIFY_ON_SUCCESS=false
"

RESTIC_OUT="ops/systemd/env.local"
if [[ "$DRY_RUN" == true ]]; then
    echo "--- ops/systemd/env.local ---"
    echo "$RESTIC_HINT"
else
    echo "$RESTIC_HINT" > "$RESTIC_OUT"
    chmod 600 "$RESTIC_OUT"
    echo "Restic env pre-fill written to: $RESTIC_OUT"
    echo "(Copy to /etc/restic/env on the VPS and fill in AWS + SMTP credentials.)"
    echo ""
fi

# ---------------------------------------------------------------------------
# Next steps
# ---------------------------------------------------------------------------
if [[ "$DRY_RUN" == false ]]; then
cat << NEXT

=== Next steps ===

1. Fill in AWS credentials in .env:
     DJANGO_AWS_ACCESS_KEY_ID, DJANGO_AWS_SECRET_ACCESS_KEY
     DJANGO_AWS_STORAGE_BUCKET_NAME

2. Deploy and bootstrap:
     make pull
     make up
     make bootstrap       # runs migrate + create_chief_editor + setup_planka_oidc

3. Set up the Planka API key:
     Open https://${DOMAIN}/backend/settings/ → "Set up Planka API key"
     Then add OIDC_ENFORCED=true to .env and run: make restart

4. Set up backups on the VPS:
     sudo bash ops/systemd/install.sh
     sudo cp ops/systemd/env.local /etc/restic/env
     # Edit /etc/restic/env — fill in AWS + SMTP credentials
     sudo chmod 600 /etc/restic/env
     sudo source /etc/restic/env && restic init
     sudo systemctl enable --now backup.timer

NEXT
fi
